#!/usr/bin/env bash
# Script to configure a brand new Ubuntu machine with Nginx and a custom 404 page

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to use the custom 404 page
# Replace the default server block in Nginx configuration with one that listens on port 80,
# uses the custom 404 page, and rewrites certain paths to redirect to Google
replacement="server {
    listen 80 default_server;
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
    location /redirect_me {
        rewrite ^ https://www.google.com permanent;
    }
}"
sudo sed -i "/^#/! s/^.*$/${replacement}/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx