#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install haproxy -y

echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 509073-web-01 52.207.208.230:80 check
        server 509073-web-02 18.204.11.104:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
