#!/usr/bin/env bash
# A bash script that creates a symbolic link in the sites-enabled directory
# that points to the default configuration file, effectively enabling the
# default site configuration in Nginx
# change the port to 80 instead of 8080
sudo ln -s -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
