#!/usr/bin/env bash
# A bash script that fixes nginx not running. Using what you did for task #0, make your fix short.
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
