#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.
# parse log for IP and HTTP
# calculate and put num occurences up front; order from greatest to least

file="apache-access.log"
awk '{print $1, $9}' $file | sort | uniq -c | sort -nr