#!/usr/bin/env bash
# Installs firewall; block all incoming except 22, 443, 80


# install ufw and ensure default values
sudo apt-get -y update
sudo apt-get -y install ufw

sudo ufw disable

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo systemctl stop ufw

# configureConfigure ufw so that it blocks all incoming traffic, except the following TCP ports:
# 22 (SSH), 443 (HTTPS SSL) and 80 (HTTP)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw reload
sudo ufw enable